---
driver:
  name: vagrant

transport:
  name: rsync

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 1
  ansible_verbose: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  http_proxy: <%= ENV['ANSIBLE_PROXY'] %>
  idempotency_test: true
  additional_copy_path:
    - extra_modules
    - filter_plugins
  ansible_vault_password_file: <%= File.expand_path(ENV['ANSIBLE_VAULT_PASSWORD_FILE'] || '') %>

platforms:
  - name: freebsd-10.3-amd64
    driver:
      box: trombik/ansible-freebsd-10.3-amd64
      box_check_update: false
    driver_config:
      ssh:
        shell: '/bin/sh'
    provisioner:
      extra_vars:
        ansible_python_interpreter: '/usr/local/bin/python'

  - name: ubuntu-14.04-amd64
    driver:
      box: trombik/ansible-ubuntu-14.04-amd64
      box_check_update: false

  - name: centos-7.2-x86_64
    driver:
      box: trombik/ansible-centos-7.2-x86_64
      box_check_update: false

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/serverspec/default.yml
    verifier:
      name: shell
      command: rspec -c -f d -I tests/serverspec tests/serverspec/default_spec.rb
