galaxy_info:
  author: ypsman
  description: This Role configures Nginx as Proxy for a single Site.
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
    - stretch
  - name: Ubuntu
    versions: all
  galaxy_tags:
  - nginx
  - proxy
  - reverse
  - webserver
  - ssl
  - http
  - https
  - ubuntu
  - debian
dependencies: []
